### ISSUE TITLE
Crash cient disconnect on usage

### ISSUE THREAD

**Issue by leagris** [blay09/TrashSlot#10]
```
Failed to handle packet for /127.0.0.1:57070
java.lang.IndexOutOfBoundsException: Index: 45, Size: 45
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_60]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_60]
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:134) ~[zs.class:?]
	at slash.event.server.PlayerClickSlotEvent.<init>(PlayerClickSlotEvent.java:43) ~[PlayerClickSlotEvent.class:?]
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:154) ~[zs.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:977) ~[nh.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[01:32:18] [Server thread/INFO]: leagris lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
```

**Comment by BlayTheNinth** [comment]
Need more information. Does it always happen or just in some scenarios?

**Comment by leagris** [comment]
I happens with [slash mod](http://www.curseforge.com/projects/223488/) installed when accessing the trash slot. (moving item over it)

**Comment by BlayTheNinth** [comment]
Slash is doing things horribly wrong, it'd be surprising if it didn't break with 90% of all mods that work closely with Minecraft code. They completely missed the point of coremods. This is not something I can or am willing to fix.

https://github.com/fihgus/Slash/issues/36
