### ISSUE TITLE
TrashSlot sometimes fails to load

### ISSUE THREAD

**Issue by ncottrill** [blay09/TrashSlot#104]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.1.22

### Mod Version

trashslot-forge-1.18.1-11.0.2

### Describe the Issue

About 25% of the time, this mod is reported to have failed to load by the server. When we first open our inventory after reboot, a red message at the top of the screen says "Trash slot mod is not loaded" (or something to that effect). And, of course, the trash slot is not visible.

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No, not on the server.

**Comment by ncottrill** [comment]
This is what I see on start-up.

[01.06 15:00:52] [Server] [modloading-worker-0/WARN] [minecolonies/]: Register mappings
[01.06 15:00:52] [Server] [modloading-worker-0/INFO] [Waila/]: Start loading plugin at net.blay09.mods.cookingforblockheads.compat.WailaAddon
[01.06 15:00:52] [Server] [modloading-worker-0/ERROR] [Waila/]: Error loading plugin at net.blay09.mods.cookingforblockheads.compat.WailaAddon
[01.06 15:00:52] [Server] java.lang.NoClassDefFoundErrormcp/mobius/waila/api/IBlockComponentProvider
[01.06 15:00:52] [Server] 	at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin}
[01.06 15:00:52] [Server] 	at java.lang.Class.forName(Class.java:375) ~[?:?] {re:mixin}
[01.06 15:00:52] [Server] 	at mcp.mobius.waila.Waila.loadComplete(Waila.java:111) ~[Jade-1.18.2-5.2.0.jar%23106!/:5.2.{re:classloading}
[01.06 15:00:52] [Server] 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
[01.06 15:00:52] [Server] 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
[01.06 15:00:52] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
[01.06 15:00:52] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
[01.06 15:00:52] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.22.jar%23160!/:?] {}
[01.06 15:00:52] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.22.jar%23159!/:?] {}
[01.06 15:00:52] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
[01.06 15:00:52] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
[01.06 15:00:52] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
[01.06 15:00:52] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
[01.06 15:00:52] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:computing_frames}
[01.06 15:00:52] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:computing_frames}
[01.06 15:00:52] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
[01.06 15:00:52] [Server] Caused byjava.lang.ClassNotFoundException: mcp.mobius.waila.api.IBlockComponentProvider
[01.06 15:00:52] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?] {}
[01.06 15:00:52] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[01.06 15:00:52] [Server] 	... more

**Comment by BlayTheNinth** [comment]
The log posted is unrelated to TrashSlot. What does the log say when it claims to have failed loading TrashSlot?

**Comment by ncottrill** [comment]
Nothing specific shows up re: Trashslot as far as I can see by searching for "trash" in the logs. The mod simply doesn't load all the time. On the next reboot, I will save the log file and note whether or not the mod loaded.

**Comment by frikinjay** [comment]
I can confirm this. And there isnt much to show in the logs. As a result owo lib handshake fails too because the client and the dedicated server single player is on have different mod list due to trash slot not loading server side.

Edit: nvm the owo lib handshake seems to be unrelated, strange stuff.

Edit: It does seem to be related, things are too random its just strange, i've removed the mod for now and things seem to be fine for now.

**Comment by BlayTheNinth** [comment]
I need a latest.log from the server of when the mod seemed to not load, even if TrashSlot isn't specifically mentioned maybe there's something else suspicious that could give a hint as to what's going on.

**Comment by breeece** [comment]
[latest.log](https://github.com/TwelveIterationMods/TrashSlot/files/11134140/latest.log)
Here's my latest where it didn't load or show up as having it installed, although this has been random for me as well. Sorry to necro this but this just started happening the other day to me.  It's just inconsistent sometimes, good thing I have an auto restart every 4 hours. :D People can just chuck their trash in lava if they REALLLLLYYY need to.
This is on 1.19.3 by the way and Forge 44.1.17 using Trash Slot 13.0.1

**Comment by BlayTheNinth** [comment]
Unfortunately that log shows nothing super suspicious that could be affecting TrashSlot. I may have to push out a version of TrashSlot with some additional logging to try and see what does and doesn't get initialized.

**Comment by chocolatechipcats** [comment]
Don't know if any much good, but here's the logs from my latest failure. (The failure is logged on line 25634 on debug.log.)

[logs.zip](https://github.com/TwelveIterationMods/TrashSlot/files/11891881/logs.zip)

It's a pretty sporadic error but  sometimes it happens several restarts (game, not just the world/server) in a row before clearing up.

**Comment by blahpers** [comment]
This has begun happening to us today.  Nothing relevant jumps out in latest.log, but debug.log did have this snippet.  Is that normal?

> [03Jul2023 12:44:37.973] [main/DEBUG] [mixin/]: Adding mixin platform agents for container SecureJarResource(trashslot)
[03Jul2023 12:44:37.973] [main/DEBUG] [mixin/]: Instancing new MixinPlatformAgentMinecraftForge for SecureJarResource(trashslot)
[03Jul2023 12:44:37.973] [main/DEBUG] [mixin/]: MixinPlatformAgentMinecraftForge rejected container SecureJarResource(trashslot)

(this is on MC 1.19.3, Forge 44.1.23, TrashSlot 13.0.1)

Edit:  Probably not, we restarted until TS started working again but the line is still there.  Weird.

**Comment by chronium** [comment]
This also happens on 1.20.1 using:
Forge 47.1.47
TrashSlot 15.0.0

**Comment by BlayTheNinth** [comment]
### If this is happening to you, please include the full logs of client **and** server, including `debug.log` if available.

A link to the modpack you're using would also help, as the only sane explanation is that some other mod is doing something insane that's interfering with TrashSlot's event handlers.

**Comment by breeece** [comment]
Months later we all just stopped playing but still happening. Ill have to
attach some logs when I can.

**Comment by BlayTheNinth** [comment]
It seems the issue occurs when the inventory is opened before PlayerLoggedInEvent is fired (which apparently can happen on long world loading times). The TrashSlot should reappear when the inventory is opened the next time.
