### ISSUE TITLE
Internal Error if you rightclick twice

### ISSUE THREAD

**Issue by TomberWolf** [blay09/TrashSlot#28]
Hey,

we're using Thermos server 1.7.10.
This mod works except of one issue: As soons as we put a stack of items into the Tray and right click it twice, Minecraft crashes with an "Internal Error".

`[18:16:12] [Server thread/WARN]: Failed to handle packet for /87.170.95.230:4933
java.lang.NullPointerException
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1793) ~[nh.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[18:16:12] [Server thread/INFO]: Tom lost connection: Internal server error`

**Comment by BlayTheNinth** [comment]
Third-party server software is not supported, especially when it's for old versions such as 1.7.10 and the server software in question is no longer being actively developed.

In 1.11 and higher the mod works differently internally so it may work better with non-standard server software then.

**Comment by TomberWolf** [comment]
Really?
Wow... that sucks.
