### ISSUE TITLE
client crash when opening chest

### ISSUE THREAD

**Issue by colemy** [blay09/TrashSlot#55]
trashslot 10.4.4 on forge 28.0.24 crashes client when opening chest

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 7/30/19 8:46 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.network.play.ServerPlayNetHandler.func_147362_b()Lnet/minecraft/network/NetworkManager;
	at net.blay09.mods.trashslot.TrashSlot.onPlayerOpenContainer(TrashSlot.java:90) ~[?:10.4.4] {}
	at net.minecraftforge.eventbus.ASMEventHandler_0_TrashSlot_onPlayerOpenContainer_Open.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraft.entity.player.ServerPlayerEntity.func_213829_a(ServerPlayerEntity.java:824) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.block.ChestBlock.func_220051_a(SourceFile:191) ~[?:?] {}
	at net.minecraft.block.BlockState.func_215687_a(BlockState.java:274) ~[?:?] {}
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:306) ~[?:?] {}
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:848) ~[?:?] {}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {}
	at net.minecraft.network.PacketThreadUtil$$Lambda$3939/383480.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:698) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:692) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:677) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:625) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1072245824 bytes (1022 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.1.0+58+1395384
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-0.10.6-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.24.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.24.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-0.16.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.24.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.24.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.0.24.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.24
	FML Language Providers: 
		javafml@28.0
	Mod List: 
		TrashSlot_1.14.3-10.4.4.jar TrashSlot {trashslot@10.4.4 DONE}
		forge-1.14.4-28.0.24-universal.jar Forge {forge@28.0.24 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['cpm9'/203, l='test', x=81.46, y=80.00, z=103.97]]
	Data Packs: vanilla, mod:trashslot, mod:forge
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by RagingGamer** [comment]
It causes crashes with blocks that opens the inventory(or has it's own?), Furnaces, chests, anvils, enchanting tables, ect. 

I just went through the painstaking task of checking all those inventory blocks with only Trash Slot installed. I'm gonna forego the logs since they'll probably look the same as yours.

**Comment by BlayTheNinth** [comment]
TrashSlot for 1.14.3 is not compatible with Minecraft 1.14.4. See #54
