### ISSUE TITLE
[1.16.3] Mod interaction crash - When in a dank storage if you trash something to the trash slot, it crashes.

### ISSUE THREAD

**Issue by ProsperCraft** [blay09/TrashSlot#82]
Latest Log-
https://gist.github.com/ProsperCraft/35781a2ba1c4692f4cf98cedcb23ba18

Crash log-
https://gist.github.com/ProsperCraft/a3293bde26faa658742cade15aec0d3a

TrashSlot_1.16.3-12.2.0.jar
dankstorage-3.11.jar

**Comment by andrewsf** [comment]
Still occurring in 12.2.1.

```
java.lang.NullPointerException: Rendering screen
	at tfar.dankstorage.client.screens.AbstractDankStorageScreen.appendDankInfo(AbstractDankStorageScreen.java:99) ~[?:3.11] {re:classloading}
	at tfar.dankstorage.client.screens.AbstractDankStorageScreen.func_231151_a_(AbstractDankStorageScreen.java:94) ~[?:3.11] {re:classloading}
	at net.blay09.mods.trashslot.client.gui.GuiHelper.renderTooltip(GuiHelper.java:23) ~[?:12.2.1] {re:classloading}
	at net.blay09.mods.trashslot.client.TrashSlotGuiHandler.onDrawScreen(TrashSlotGuiHandler.java:245) ~[?:12.2.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_2238_TrashSlotGuiHandler_onDrawScreen_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:287) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
```
